build-windows:
  script: git-bash build-win32.sh
  tags:
    - windows-i386
build-linux-i386:
  script: bash build_deb.sh
  tags:
    - linux-i386
build-linux-x86-64:
  script: bash build_deb.sh
  tags:
    - linux-x64