before_script:
  - git submodule sync
  - git submodule update --init --recursive

build-windows:
  script: git-bash build-win32.sh
  tags:
    - windows-i386
build-linux-i386:
  script:
    - lazbuild fhem2mqtt.lpi
    - bash build_deb.sh
  tags:
    - linux-i386
build-linux-x86-64:
  script: 
    - lazbuild fhem2mqtt.lpi
    - bash build_deb.sh
  tags:
    - linux-x64
